FROM node:18 AS build

WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
RUN npm run build

# --- runtime nginx ---
FROM nginx:1.25
COPY --from=build /app/dist /usr/share/nginx/html

# serve via nginx
EXPOSE 80
